//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sobiens.Web.Components.Tutorials.SobyTabs
{


    public partial class GettingStarted
    {

        /// <summary>
        /// SobyTabsSideMenuControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sobiens.Web.Components.Controls.SobyTabsSideMenuControl SobyTabsSideMenuControl;
    }
}
